CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_SLEEP=n

# Prospector configs
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80

# Core USB keyboard
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_BOOT=y

# Keep keyboard HID simple
CONFIG_ZMK_HID_KEYBOARD_REPORT_USAGES_BASIC=y
CONFIG_ZMK_HID_KEYBOARD_NKRO=y
CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=n

# DO NOT expose extra USB interfaces
CONFIG_ZMK_STUDIO=n          # turn off ZMK Studio
CONFIG_ZMK_USB_LOGGING=n     # no USB logging
CONFIG_LOG=n                 # if you don't absolutely need logs over USB
CONFIG_SERIAL=n              # no extra CDC/serial if you have it enabled

# Prefer simpler HID reports
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
# Avoid extended NKRO reports if you had them on
CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=n

#CONFIG_ZMK_USB_LOGGING=y
#CONFIG_LOG_MODE_IMMEDIATE=n
#CONFIG_LOG_TIMESTAMP_64BIT=y
#CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=5000
#CONFIG_ZMK_LOG_LEVEL_DBG=y
#CONFIG_KSCAN_LOG_LEVEL_INF=y
