# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Totem Prospector'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["xiao_ble"]'
      shield: '["totem_left","totem_right","totem_dongle prospector_adapter","settings_reset"]'
      # modules: '["carrefinho/prospector-zmk-module/feat/new-status-screens"]'
      # shield: '["totem_dongle"]'
