# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Totem Prospector'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeduino_xiao_ble"]'
      shield: '["totem_left","totem_right","totem_dongle prospector_adapter","settings_reset"]'
      modules: '["carrefinho/prospector-zmk-module/main"]'
      branches: '["zmkfirmware/zmk/v0.3.0"]'
      # shield: '["totem_dongle"]'
