# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Toucan Prospector'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["toucan_left rgbled_adapter toucan_pet","toucan_right rgbled_adapter","toucan_dongle rgbled_adapter prospector_adapter", "settings_reset"]'
      modules: '["caksoylar/zmk-rgbled-widget/v0.3-branch geeksville/cirque-input-module/toucan carrefinho/prospector-zmk-module/main"]'
      branches: '["zmkfirmware/zmk/v0.3"]'

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Rename firmware files
        run: |
          mkdir firmware
          for dir in artifacts/*/; do
            name=$(basename "$dir")
            cp "$dir/zephyr.uf2" "firmware/${name}.uf2"
          done

      - name: Upload combined archive
        uses: actions/upload-artifact@v4
        with:
          name: toucan-prospector-firmware
          path: firmware/

      - name: Delete individual artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            *
          excludes: toucan-prospector-firmware
