# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Toucan Prospector'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["toucan_left rgbled_adapter toucan_pet","toucan_right rgbled_adapter","toucan_dongle rgbled_adapter prospector_adapter", "settings_reset"]'
      modules: '["caksoylar/zmk-rgbled-widget/v0.3-branch geeksville/cirque-input-module/toucan carrefinho/prospector-zmk-module/main"]'
      branches: '["zmkfirmware/zmk/v0.3"]'
