# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Toucan'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["xiao_ble//zmk"]'
      shield: '["toucan_left","toucan_right","settings_reset"]'
